site_name: Tomas Perez
theme:
  name: material

  palette:
    primary: blue grey
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - "Home": "index.md"
  - "Experience": "experience.md"
  - "Tech Stack": "tech_stack.md"
  - "Certifications": "certifications.md"
  - "Interests": "interests.md"
  - "Projects":
      - "Loan Management System": "projects/loan-management-system.md"

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tomas-perez-alvarez/
    - icon: fontawesome/brands/github
      link: https://github.com/Tomperez98

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
