site_name: Tomas Perez
theme:
  name: material
  palette:
    primary: blue grey
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Home: index.md
  - Experience: experience.md
  - Tech Stack: tech_stack.md
  - Certifications: certifications.md
  - Interests: interests.md
  - Education: education.md
