site_name: Tomas Perez
theme:
  name: material

  palette:
    primary: blue grey
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.prune
    - navigation.top

nav:
  - "Home":
      - index.md
      - "Experience": experience.md
      - "Tech Stack": tech-stack.md
      - "Certifications": certifications.md
      - "Interests": interests.md
  - "Projects":
      - "Loan Management System": projects/loan-management-system.md
  - "Notes AWS":
      - "Shared Responsability Model": notes-aws/shared-responsability-model.md
      - "Well-Architected Framework":
          - "Framework": notes-aws/well-architected-framework/framework.md
          - "Pillars":
              - "Operational Excellence":
                  - "Definition": notes-aws/well-architected-framework/pillars/operation-excellence/definition.md
                  - "Best Practices":
                      - "Organization": notes-aws/well-architected-framework/pillars/operation-excellence/best-practices/organization.md
                      - "Prepare": notes-aws/well-architected-framework/pillars/operation-excellence/best-practices/prepare.md
                      - "Operate": notes-aws/well-architected-framework/pillars/operation-excellence/best-practices/operate.md
                      - "Evolve": notes-aws/well-architected-framework/pillars/operation-excellence/best-practices/evolve.md
              - "Security":
                  - "Definition": notes-aws/well-architected-framework/pillars/security/definition.md
                  - "Best Practices":
                      - "Security": notes-aws/well-architected-framework/pillars/security/best-practices/security.md
                      - "Identity and Access Management": notes-aws/well-architected-framework/pillars/security/best-practices/identity-and-access-mngt.md
                      - "Detection": notes-aws/well-architected-framework/pillars/security/best-practices/detection.md
                      - "Infrastructure Protection": notes-aws/well-architected-framework/pillars/security/best-practices/infrastructure-protection.md
                      - "Data Protection": notes-aws/well-architected-framework/pillars/security/best-practices/data-protection.md
                      - "Incident Response": notes-aws/well-architected-framework/pillars/security/best-practices/incident-response.md
              - "Reliability":
                  - "Definition": notes-aws/well-architected-framework/pillars/reliability/definition.md
                  - "Best Practices":
                      - "Foundations": notes-aws/well-architected-framework/pillars/reliability/best-practices/foundations.md
                      - "Workload Architecture": notes-aws/well-architected-framework/pillars/reliability/best-practices/workload-architecture.md
                      - "Change Management": notes-aws/well-architected-framework/pillars/reliability/best-practices/change-management.md
                      - "Failure Management": notes-aws/well-architected-framework/pillars/reliability/best-practices/failure-management.md
              - "Performance Efficiency":
                  - "Definition": notes-aws/well-architected-framework/pillars/perf-efficiency/definition.md
                  - "Best Practices":
                      - "Selection":
                          - notes-aws/well-architected-framework/pillars/perf-efficiency/best-practices/selection/index.md
                          - "Compute": notes-aws/well-architected-framework/pillars/perf-efficiency/best-practices/selection/compute.md
                          - "Storage": notes-aws/well-architected-framework/pillars/perf-efficiency/best-practices/selection/storage.md
                          - "Database": notes-aws/well-architected-framework/pillars/perf-efficiency/best-practices/selection/database.md
                          - "Network": notes-aws/well-architected-framework/pillars/perf-efficiency/best-practices/selection/network.md
                      - "Review": notes-aws/well-architected-framework/pillars/perf-efficiency/best-practices/review.md
                      - "Monitoring": notes-aws/well-architected-framework/pillars/perf-efficiency/best-practices/monitoring.md
                      - "Tradeoffs": notes-aws/well-architected-framework/pillars/perf-efficiency/best-practices/tradeoffs.md
              - "Cost Optimization":
                  - "Definition": notes-aws/well-architected-framework/pillars/cost-optimization/definition.md
                  - "Best Practices":
                      - "Practice Cloud Financial Management": notes-aws/well-architected-framework/pillars/cost-optimization/best-practices/cloud-financial-mgmt.md
                      - "Expenditure and usage awareness": notes-aws/well-architected-framework/pillars/cost-optimization/best-practices/exp-and-usg-awareness.md
                      - "Cost-effective resources": notes-aws/well-architected-framework/pillars/cost-optimization/best-practices/cost-effective-resources.md
                      - "Manage demand and supply resources": notes-aws/well-architected-framework/pillars/cost-optimization/best-practices/mgn-sup-dem-resources.md
                      - "Optimize over time": notes-aws/well-architected-framework/pillars/cost-optimization/best-practices/optimize-over-time.md
              - "Sustainability":
                  - "Definition": notes-aws/well-architected-framework/pillars/sustainability/definition.md
                  - "Best Practices":
                      - "Region selection": notes-aws/well-architected-framework/pillars/sustainability/best-practices/region-selection.md
                      - "User behavior patterns": notes-aws/well-architected-framework/pillars/sustainability/best-practices/user-behavior-patterns.md
                      - "Software and architecture patterns": notes-aws/well-architected-framework/pillars/sustainability/best-practices/swe-and-arch-patterns.md
                      - "Data Patterns": notes-aws/well-architected-framework/pillars/sustainability/best-practices/data-patterns.md
                      - "Hardware patterns": notes-aws/well-architected-framework/pillars/sustainability/best-practices/hardware-patterns.md
                      - "Development and deployment patterns": notes-aws/well-architected-framework/pillars/sustainability/best-practices/dev-and-deploy-patterns.md
          - "The Review Process": notes-aws/well-architected-framework/review-process.md
          - "Conclusion": notes-aws/well-architected-framework/conclusion.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tomas-perez-alvarez/
    - icon: fontawesome/brands/github
      link: https://github.com/Tomperez98/blog

extra_css:
  - stylesheets/extra.css

# See https://github.com/squidfunk/mkdocs-material/issues/1143#issuecomment-504640100
plugins: []

markdown_extensions:
  - attr_list
  - tables
  - pymdownx.emoji:
      "emoji_index": !!python/name:materialx.emoji.twemoji
      "emoji_generator": !!python/name:materialx.emoji.to_svg
