site_name: Tomas Perez
theme:
  name: material

  palette:
    primary: blue grey
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - "Home": "index.md"
  - "Experience": "experience.md"
  - "Tech Stack": "tech_stack.md"
  - "Certifications": "certifications.md"
  - "Interests": "interests.md"
  - "Projects":
      - "Loan Management System": "projects/loan-management-system.md"
  - "Notes AWS":
      - "Well-Architected Framework":
          - "Framework": "notes_aws/well_architected_framework/framework.md"
          - "Pillars":
              - "Operational Excellence":
                  - "Definition": "notes_aws/well_architected_framework/pillars/operation_excellence/definition.md"
                  - "Best Practices":
                      - "Organization": "notes_aws/well_architected_framework/pillars/operation_excellence/best_practices/organization.md"
                      - "Prepare": "notes_aws/well_architected_framework/pillars/operation_excellence/best_practices/prepare.md"
                      - "Operate": "notes_aws/well_architected_framework/pillars/operation_excellence/best_practices/operate.md"
                      - "Evolve": "notes_aws/well_architected_framework/pillars/operation_excellence/best_practices/evolve.md"

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tomas-perez-alvarez/
    - icon: fontawesome/brands/github
      link: https://github.com/Tomperez98/blog

markdown_extensions:
  - pymdownx.emoji:
      "emoji_index": !!python/name:materialx.emoji.twemoji
      "emoji_generator": !!python/name:materialx.emoji.to_svg
