site_name: My Docs
theme:
  name: material
  palette:
    primary: blue grey
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
